events {}

http {
  server {
    listen 443 ssl;
    server_name web-app-fineract-fiter.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/web-app-fineract-fiter.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/web-app-fineract-fiter.duckdns.org/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}